name: Build on release

on:
#  schedule:
#    - cron: 0 6 * * 1,4
  release:
    types: [ published ]

jobs:

  # For dockerhub: build images via build_php workflow
  dockerhub-build-php-images:
    if: ${{ github.event.release.prerelease == false }}
    uses: ./.github/workflows/build_php.yml
    secrets: inherit
    with:
      image: php
      registry: adeliom
      image_suffix: '-{{latest_release_tag}}'
      push_image: true

  # For dockerhub: upgrade readme doc
  dockerhub-php-doc:
    if: ${{ github.event.release.prerelease == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: adeliom/php
          readme-filepath: ./php/README.md

  # For github package: build images via build_php workflow
  ghcr-build-php-images:
    if: ${{ github.event.release.prerelease == false }}
    uses: ./.github/workflows/build_php.yml
    secrets: inherit
    with:
      image: php
      registry: ghcr.io/agence-adeliom
      image_suffix: '-{{latest_release_tag}}'
      push_image: true

  # For dockerhub: build images via build_redis workflow
  dockerhub-build-redis-images:
    if: ${{ github.event.release.prerelease == false }}
    uses: ./.github/workflows/build_redis.yml
    secrets: inherit
    with:
      image: redis
      registry: adeliom
      image_suffix: '-{{latest_release_tag}}'
      push_image: true

  # For github package: build images via build_php workflow
  ghcr-build-redis-images:
    if: ${{ github.event.release.prerelease == false }}
    uses: ./.github/workflows/build_redis.yml
    secrets: inherit
    with:
      image: redis
      registry: ghcr.io/agence-adeliom
      image_suffix: '-{{latest_release_tag}}'
      push_image: true

  # For dockerhub: upgrade redis readme doc
  dockerhub-redis-doc:
    if: ${{ github.event.release.prerelease == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: adeliom/redis
          readme-filepath: ./redis/README.md
